parameters:
    # The directory (inside each bundle) where to look for migrations definitions
    # NB: this pasrasmeter will be renamed in v3
    kaliop_bundle_migration.version_directory: 'MigrationVersions'
    # The dtabase table used to store migration information. Will be created automatically
    ez_migration_bundle.table_name: 'kaliop_migrations'
    # Used to discriminate valid migration definitions
    ez_migration_bundle.valid_databases:
        # names have to correspond to doctrine 'platform', short of version numbers and lowercase
        # NB: this does NOT mean that eZPublish supports all of them :-)
        - 'mysql'
        - 'postgresql'
        - 'oracle'
        - 'sqlite'
        - 'drizzle'
        - 'sqlserver'
        - 'sqlanywhere'

    # Deprecated paremeter. Left in for the v1-to-v2 migration to work. Will be removed in v3
    kaliop_bundle_migration.table_name: 'kaliop_versions'

    ez_migration_bundle.migration_service.class: Kaliop\eZMigrationBundle\Core\MigrationService

    ez_migration_bundle.loader.filesystem.class: Kaliop\eZMigrationBundle\Core\Loader\Filesystem

    ez_migration_bundle.definition_parser.yaml.class: Kaliop\eZMigrationBundle\Core\DefinitionParser\PHPDefinitionParser
    ez_migration_bundle.definition_parser.sql.class: Kaliop\eZMigrationBundle\Core\DefinitionParser\SQLDefinitionParser
    ez_migration_bundle.definition_parser.php.class: Kaliop\eZMigrationBundle\Core\DefinitionParser\YamlDefinitionParser

    ez_migration_bundle.storage_handler.database.class: Kaliop\eZMigrationBundle\Core\StorageHandler\Database

    ez_migration_bundle.executor.php.class: Kaliop\eZMigrationBundle\Core\Executor\PHPExecutor
    ez_migration_bundle.executor.sql.class: Kaliop\eZMigrationBundle\Core\Executor\SQLExecutor
    ez_migration_bundle.executor.repository.class: Kaliop\eZMigrationBundle\Core\Executor\RepositoryExecutor

    ez_migration_bundle.executor.content_manager.class: Kaliop\eZMigrationBundle\Core\Executor\ContentManager
    ez_migration_bundle.executor.content_type_manager.class: Kaliop\eZMigrationBundle\Core\Executor\ContentTypeManager
    ez_migration_bundle.executor.location_manager.class: Kaliop\eZMigrationBundle\Core\Executor\LocationManager
    ez_migration_bundle.executor.role_manager.class: Kaliop\eZMigrationBundle\Core\Executor\RoleManager
    ez_migration_bundle.executor.tag_manager.class: Kaliop\eZMigrationBundle\Core\Executor\TagManager
    ez_migration_bundle.executor.user_group_manager.class: Kaliop\eZMigrationBundle\Core\Executor\UserGroupManager
    ez_migration_bundle.executor.user_manager.class: Kaliop\eZMigrationBundle\Core\Executor\UserManager
    ez_migration_bundle.executor.language_manager.class: Kaliop\eZMigrationBundle\Core\Executor\LanguageManager

    ez_migration_bundle.content_matcher.class: Kaliop\eZMigrationBundle\Core\Matcher\ContentMatcher
    ez_migration_bundle.location_matcher.class: Kaliop\eZMigrationBundle\Core\Matcher\LocationMatcher
    ez_migration_bundle.user_matcher.class: Kaliop\eZMigrationBundle\Core\Matcher\UserMatcher
    ez_migration_bundle.user_group_matcher.class: Kaliop\eZMigrationBundle\Core\Matcher\UserGroupMatcher
    ez_migration_bundle.role_matcher.class: Kaliop\eZMigrationBundle\Core\Matcher\RoleMatcher
    ez_migration_bundle.content_type_matcher.class: Kaliop\eZMigrationBundle\Core\Matcher\ContentTypeMatcher
    ez_migration_bundle.section_matcher.class: Kaliop\eZMigrationBundle\Core\Matcher\SectionMatcher
    ez_migration_bundle.object_state_matcher.class: Kaliop\eZMigrationBundle\Core\Matcher\ObjectStateMatcher
    ez_migration_bundle.content_type_group_matcher.class: Kaliop\eZMigrationBundle\Core\Matcher\ContentTypeGroupMatcher

    ez_migration_bundle.complex_field_manager.class: Kaliop\eZMigrationBundle\Core\ComplexField\ComplexFieldManager
    ez_migration_bundle.complex_field.ezauthor.class: Kaliop\eZMigrationBundle\Core\ComplexField\EzAuthor
    ez_migration_bundle.complex_field.ezbinaryfile.class: Kaliop\eZMigrationBundle\Core\ComplexField\EzBinaryFile
    ez_migration_bundle.complex_field.ezimage.class: Kaliop\eZMigrationBundle\Core\ComplexField\EzImage
    ez_migration_bundle.complex_field.ezpage.class: Kaliop\eZMigrationBundle\Core\ComplexField\EzPage
    ez_migration_bundle.complex_field.ezrelation.class: Kaliop\eZMigrationBundle\Core\ComplexField\EzRelation
    ez_migration_bundle.complex_field.ezrelationlist.class: Kaliop\eZMigrationBundle\Core\ComplexField\EzRelationList
    ez_migration_bundle.complex_field.ezrichtext.class: Kaliop\eZMigrationBundle\Core\ComplexField\EzRichText
    ez_migration_bundle.complex_field.ezxmltext.class: Kaliop\eZMigrationBundle\Core\ComplexField\EzXmlText

    ez_migration_bundle.reference_resolver.chain.class: Kaliop\eZMigrationBundle\Core\ReferenceResolver\ChainResolver
    ez_migration_bundle.reference_resolver.customreference.class: Kaliop\eZMigrationBundle\Core\ReferenceResolver\CustomReferenceResolver
    ez_migration_bundle.reference_resolver.content.class: Kaliop\eZMigrationBundle\Core\ReferenceResolver\ContentResolver
    ez_migration_bundle.reference_resolver.location.class: Kaliop\eZMigrationBundle\Core\ReferenceResolver\LocationResolver
    ez_migration_bundle.reference_resolver.tag.class: Kaliop\eZMigrationBundle\Core\ReferenceResolver\TagResolver

    ez_migration_bundle.helper.limitation_converter.class: Kaliop\eZMigrationBundle\Core\Helper\LimitationConverter
    ez_migration_bundle.helper.console_io.class: Kaliop\eZMigrationBundle\Core\Helper\ConsoleIO

services:

    ez_migration_bundle.migration_service:
        class: '%ez_migration_bundle.migration_service.class%'
        arguments:
            - '@ez_migration_bundle.loader'
            - '@ez_migration_bundle.storage_handler'
            - '@ezpublish.api.repository'
            - '@event_dispatcher'

    ### loaders

    ez_migration_bundle.loader:
        alias: ez_migration_bundle.loader.filesystem

    ez_migration_bundle.loader.filesystem:
        class: '%ez_migration_bundle.loader.filesystem.class%'
        arguments:
            - '@kernel'
            - '%kaliop_bundle_migration.version_directory%'

    ### parsers

    ez_migration_bundle.definition_parser.yaml:
        class: '%ez_migration_bundle.definition_parser.yaml.class%'
        arguments: []
        tags:
            - { name: ez_migration_bundle.definition_parser }

    ez_migration_bundle.definition_parser.sql:
        class: '%ez_migration_bundle.definition_parser.sql.class%'
        arguments:
            - '%ez_migration_bundle.valid_databases%'
        tags:
            - { name: ez_migration_bundle.definition_parser }

    ez_migration_bundle.definition_parser.php:
        class: '%ez_migration_bundle.definition_parser.php.class%'
        arguments: []
        tags:
            - { name: ez_migration_bundle.definition_parser }

    ### storage handlers

    ez_migration_bundle.storage_handler:
        alias: ez_migration_bundle.storage_handler.database

    ez_migration_bundle.storage_handler.database:
        class: '%ez_migration_bundle.storage_handler.database.class%'
        arguments:
            - '@ezpublish.connection'
            - '%ez_migration_bundle.table_name%'

    ### executors

    ez_migration_bundle.executor.php:
        class: '%ez_migration_bundle.executor.php.class%'
        arguments:
            - '@service_container'
        tags:
            - { name: ez_migration_bundle.executor }

    ez_migration_bundle.executor.sql:
        class: '%ez_migration_bundle.executor.sql.class%'
        arguments:
            - '@ezpublish.connection'
        tags:
            - { name: ez_migration_bundle.executor }

    ez_migration_bundle.executor.repository:
        abstract: true
        class: '%ez_migration_bundle.executor.repository.class%'
        calls:
            - ['setRepository', ['@ezpublish.api.repository']]
            - ['setReferenceResolver', ['@ez_migration_bundle.reference_resolver.customreference']]

    ez_migration_bundle.executor.content_manager:
        parent: ez_migration_bundle.executor.repository
        class: '%ez_migration_bundle.executor.content_manager.class%'
        arguments:
            - '@ez_migration_bundle.content_matcher'
            - '@ez_migration_bundle.section_matcher'
            - '@ez_migration_bundle.user_matcher'
            - '@ez_migration_bundle.object_state_matcher'
            - '@ez_migration_bundle.complex_field_manager'
            - '@ez_migration_bundle.executor.location_manager'
        tags:
            - { name: ez_migration_bundle.executor }

    ez_migration_bundle.executor.location_manager:
        parent: ez_migration_bundle.executor.repository
        class: '%ez_migration_bundle.executor.location_manager.class%'
        arguments:
            - '@ez_migration_bundle.content_matcher'
            - '@ez_migration_bundle.location_matcher'
        tags:
            - { name: ez_migration_bundle.executor }

    ez_migration_bundle.executor.content_type_manager:
        parent: ez_migration_bundle.executor.repository
        class: '%ez_migration_bundle.executor.content_type_manager.class%'
        arguments:
            - '@ez_migration_bundle.content_type_matcher'
            - '@ez_migration_bundle.content_type_group_matcher'
        tags:
            - { name: ez_migration_bundle.executor }

    ez_migration_bundle.executor.user_manager:
        parent: ez_migration_bundle.executor.repository
        class: '%ez_migration_bundle.executor.user_manager.class%'
        arguments:
            - '@ez_migration_bundle.user_matcher'
        tags:
            - { name: ez_migration_bundle.executor }

    ez_migration_bundle.executor.user_group_manager:
        parent: ez_migration_bundle.executor.repository
        class: '%ez_migration_bundle.executor.user_group_manager.class%'
        arguments:
            - '@ez_migration_bundle.user_group_matcher'
            - '@ez_migration_bundle.role_matcher'
        tags:
            - { name: ez_migration_bundle.executor }

    ez_migration_bundle.executor.role_manager:
        class: '%ez_migration_bundle.executor.role_manager.class%'
        parent: ez_migration_bundle.executor.repository
        arguments:
            - '@ez_migration_bundle.role_matcher'
            - '@ez_migration_bundle.helper.limitation_converter'
        tags:
            - { name: ez_migration_bundle.executor }

    ez_migration_bundle.executor.language_manager:
        class: '%ez_migration_bundle.executor.language_manager.class%'
        parent: ez_migration_bundle.executor.repository
        tags:
            - { name: ez_migration_bundle.executor }

    ez_migration_bundle.executor.tag_manager:
        parent: ez_migration_bundle.executor.repository
        class: '%ez_migration_bundle.executor.tag_manager.class%'
        arguments:
            - '@?ezpublish.api.service.tags'
        tags:
            - { name: ez_migration_bundle.executor }

    ### matchers

    ez_migration_bundle.content_matcher:
        class: '%ez_migration_bundle.content_matcher.class%'
        arguments:
            - '@ezpublish.api.repository'

    ez_migration_bundle.location_matcher:
        class: '%ez_migration_bundle.location_matcher.class%'
        arguments:
            - '@ezpublish.api.repository'

    ez_migration_bundle.user_matcher:
        class: '%ez_migration_bundle.user_matcher.class%'
        arguments:
            - '@ezpublish.api.repository'

    ez_migration_bundle.user_group_matcher:
        class: '%ez_migration_bundle.user_group_matcher.class%'
        arguments:
            - '@ezpublish.api.repository'

    ez_migration_bundle.role_matcher:
        class: '%ez_migration_bundle.role_matcher.class%'
        arguments:
            - '@ezpublish.api.repository'

    ez_migration_bundle.content_type_matcher:
        class: '%ez_migration_bundle.content_type_matcher.class%'
        arguments:
            - '@ezpublish.api.repository'

    ez_migration_bundle.section_matcher:
        class: '%ez_migration_bundle.section_matcher.class%'
        arguments:
            - '@ezpublish.api.repository'

    ez_migration_bundle.object_state_matcher:
        class: '%ez_migration_bundle.object_state_matcher.class%'
        arguments:
            - '@ezpublish.api.repository'

    ez_migration_bundle.content_type_group_matcher:
        class: '%ez_migration_bundle.content_type_group_matcher.class%'
        arguments:
            - '@ezpublish.api.repository'

    ### field handlers

    ez_migration_bundle.complex_field_manager:
        class: '%ez_migration_bundle.complex_field_manager.class%'
        arguments:
             - '@ezpublish.api.service.field_type'
        #    - '@ezpublish.api.repository'
        #    - '@service_container'

    ez_migration_bundle.complex_field:
        abstract: true
        calls:
            - ['setReferenceResolver', ['@ez_migration_bundle.reference_resolver.customreference']]

    ez_migration_bundle.complex_field.ezauthor:
        parent: ez_migration_bundle.complex_field
        class: '%ez_migration_bundle.complex_field.ezauthor.class%'
        tags:
            - { name: ez_migration_bundle.complex_field, fieldtype: ezauthor }

    ez_migration_bundle.complex_field.ezbinaryfile:
        parent: ez_migration_bundle.complex_field
        class: '%ez_migration_bundle.complex_field.ezbinaryfile.class%'
        tags:
            - { name: ez_migration_bundle.complex_field, fieldtype: ezbinaryfile }

    ez_migration_bundle.complex_field.ezimage:
        parent: ez_migration_bundle.complex_field
        class: '%ez_migration_bundle.complex_field.ezimage.class%'
        tags:
            - { name: ez_migration_bundle.complex_field, fieldtype: ezimage }

    ez_migration_bundle.complex_field.ezpage:
        parent: ez_migration_bundle.complex_field
        class: '%ez_migration_bundle.complex_field.ezpage.class%'
        arguments:
            - '@ezpublish.fieldType.ezpage.pageService'
        tags:
            - { name: ez_migration_bundle.complex_field, fieldtype: ezpage }

    ez_migration_bundle.complex_field.ezrelation:
        parent: ez_migration_bundle.complex_field
        class: '%ez_migration_bundle.complex_field.ezrelation.class%'
        arguments:
            - '@ez_migration_bundle.content_matcher'
        tags:
            - { name: ez_migration_bundle.complex_field, fieldtype: ezobjectrelation }

    ez_migration_bundle.complex_field.ezrelationlist:
        parent: ez_migration_bundle.complex_field
        class: '%ez_migration_bundle.complex_field.ezrelationlist.class%'
        arguments:
            - '@ez_migration_bundle.content_matcher'
        tags:
            - { name: ez_migration_bundle.complex_field, fieldtype: ezobjectrelationlist }

    ez_migration_bundle.complex_field.ezrichtext:
        parent: ez_migration_bundle.complex_field
        class: '%ez_migration_bundle.complex_field.ezrichtext.class%'
        arguments:
            - '@ez_migration_bundle.content_matcher'
            - '@ez_migration_bundle.location_matcher'
        tags:
            - { name: ez_migration_bundle.complex_field, fieldtype: ezrichtext }

    ez_migration_bundle.complex_field.ezxmltext:
        parent: ez_migration_bundle.complex_field
        class: '%ez_migration_bundle.complex_field.ezxmltext.class%'
        arguments:
            - '@ez_migration_bundle.content_matcher'
            - '@ez_migration_bundle.location_matcher'
        tags:
            - { name: ez_migration_bundle.complex_field, fieldtype: ezxmltext }

    ### reference resolvers

    # A service that will resolve *any* possible reference. To be used with care
    ez_migration_bundle.reference_resolver:
        alias: ez_migration_bundle.reference_resolver.chain

    ez_migration_bundle.reference_resolver.chain:
        class: '%ez_migration_bundle.reference_resolver.chain.class%'
        arguments:
            -
                - '@ez_migration_bundle.reference_resolver.customreference'
                - '@ez_migration_bundle.reference_resolver.location'
               # not enabled by default for v2, as it might break v1 migrations that don't expect it to be present
               #- '@ez_migration_bundle.reference_resolver.content'
                - '@ez_migration_bundle.reference_resolver.tag'

    # @deprecated
    ez_migration_bundle.reference_resolver.content:
        class: '%ez_migration_bundle.reference_resolver.content.class%'
        arguments:
            - '@ezpublish.api.repository'

    ez_migration_bundle.reference_resolver.location:
        class: '%ez_migration_bundle.reference_resolver.location.class%'
        arguments:
            - '@ezpublish.api.repository'

    ez_migration_bundle.reference_resolver.tag:
        class: '%ez_migration_bundle.reference_resolver.tag.class%'
        arguments:
            - '@ezpublish.translation_helper'
            - '@?ezpublish.api.service.tags'

    # A service which resolves *only* custom references. As such, it is used in most places
    ez_migration_bundle.reference_resolver.customreference:
        alias: ez_migration_bundle.reference_resolver.customreference.flexible

    ez_migration_bundle.reference_resolver.customreference.base:
        class: '%ez_migration_bundle.reference_resolver.customreference.class%'
        arguments: []

    # NB: This service will see added to the chain any service tagged as 'ez_migration_bundle.reference_resolver.customreference'
    ez_migration_bundle.reference_resolver.customreference.flexible:
        class: '%ez_migration_bundle.reference_resolver.chain.class%'
        arguments:
            - [ '@ez_migration_bundle.reference_resolver.customreference.base' ]

    ### misc

    ez_migration_bundle.helper.limitation_converter:
        class: '%ez_migration_bundle.helper.limitation_converter.class%'
        arguments:
            - '%ezpublish.siteaccess.list%'
            - '@ez_migration_bundle.location_matcher'
            - '@ez_migration_bundle.section_matcher'
            - '@ez_migration_bundle.content_type_matcher'

    ez_migration_bundle.helper.console_io:
        class: '%ez_migration_bundle.helper.console_io.class%'
        tags:
            - { name: kernel.event_listener, event: console.command }
